// Quiz niches - 9 ClickBank funnels
export const quizNiches = [
  {
    id: 'weight-loss',
    title: 'Weight Loss',
    subtitle: 'Find your perfect plan',
    emoji: '🔥',
    color: '#FF5A5F',
    href: '/quiz/weight-loss',
    image: 'https://picsum.photos/seed/weightloss/400/300',
    participants: '12,400+',
  },
  {
    id: 'fitness',
    title: 'Home Fitness',
    subtitle: 'Build your ideal routine',
    emoji: '💪',
    color: '#00A699',
    href: '/quiz/fitness',
    image: 'https://picsum.photos/seed/fitness/400/300',
    participants: '9,800+',
  },
  {
    id: 'keto',
    title: 'Keto & Diet',
    subtitle: 'Match your metabolism',
    emoji: '🥗',
    color: '#FF5A5F',
    href: '/quiz/keto',
    image: 'https://picsum.photos/seed/keto/400/300',
    participants: '7,200+',
  },
  {
    id: 'skincare',
    title: 'Skincare',
    subtitle: 'Glow up your routine',
    emoji: '✨',
    color: '#00A699',
    href: '/quiz/skincare',
    image: 'https://picsum.photos/seed/skincare/400/300',
    participants: '15,100+',
  },
  {
    id: 'sleep',
    title: 'Better Sleep',
    subtitle: 'Wake up refreshed',
    emoji: '😴',
    color: '#FF5A5F',
    href: '/quiz/sleep',
    image: 'https://picsum.photos/seed/sleep/400/300',
    participants: '6,500+',
  },
  {
    id: 'anxiety',
    title: 'Stress & Anxiety',
    subtitle: 'Find your calm',
    emoji: '🧘',
    color: '#00A699',
    href: '/quiz/anxiety',
    image: 'https://picsum.photos/seed/anxiety/400/300',
    participants: '8,900+',
  },
  {
    id: 'testosterone',
    title: "Men's Health",
    subtitle: "Optimize your levels",
    emoji: '⚡',
    color: '#FF5A5F',
    href: '/quiz/testosterone',
    image: 'https://picsum.photos/seed/menshealth/400/300',
    participants: '5,700+',
  },
  {
    id: 'make-money',
    title: 'Make Money Online',
    subtitle: 'Find your income path',
    emoji: '💰',
    color: '#00A699',
    href: '/quiz/make-money',
    image: 'https://picsum.photos/seed/makemoney/400/300',
    participants: '18,300+',
  },
  {
    id: 'relationships',
    title: 'Relationships',
    subtitle: 'Strengthen your bond',
    emoji: '❤️',
    color: '#FF5A5F',
    href: '/quiz/relationships',
    image: 'https://picsum.photos/seed/relationships/400/300',
    participants: '11,600+',
  },
];

// Shop categories - 6 CJDropshipping
export const shopCategories = [
  {
    id: 'fitness-gear',
    title: 'Fitness Gear',
    description: 'Home gym essentials',
    image: 'https://picsum.photos/seed/fitnessgear/600/400',
    href: '/shop/fitness-gear',
    itemCount: '240+ items',
  },
  {
    id: 'wellness',
    title: 'Wellness',
    description: 'Health & self-care',
    image: 'https://picsum.photos/seed/wellness/600/400',
    href: '/shop/wellness',
    itemCount: '180+ items',
  },
  {
    id: 'kitchen',
    title: 'Kitchen & Diet',
    description: 'Cook smarter',
    image: 'https://picsum.photos/seed/kitchen/600/400',
    href: '/shop/kitchen',
    itemCount: '320+ items',
  },
  {
    id: 'beauty',
    title: 'Beauty',
    description: 'Look & feel your best',
    image: 'https://picsum.photos/seed/beauty/600/400',
    href: '/shop/beauty',
    itemCount: '410+ items',
  },
  {
    id: 'tech',
    title: 'Tech & Gadgets',
    description: 'Smart tools for life',
    image: 'https://picsum.photos/seed/techgadgets/600/400',
    href: '/shop/tech',
    itemCount: '290+ items',
  },
  {
    id: 'lifestyle',
    title: 'Lifestyle',
    description: 'Level up every day',
    image: 'https://picsum.photos/seed/lifestyle/600/400',
    href: '/shop/lifestyle',
    itemCount: '200+ items',
  },
];

// Featured products - placeholder (will be WP REST API driven)
export const featuredProducts = [
  {
    id: 1,
    title: 'ProFlex Resistance Bands Set',
    price: '$24.99',
    originalPrice: '$49.99',
    rating: 4.8,
    reviews: 1240,
    image: 'https://picsum.photos/seed/resistancebands/400/400',
    badge: 'Best Seller',
    href: '/shop/product/proflex-bands',
  },
  {
    id: 2,
    title: 'Keto Meal Prep Container Kit',
    price: '$18.99',
    originalPrice: '$34.99',
    rating: 4.6,
    reviews: 890,
    image: 'https://picsum.photos/seed/mealprep/400/400',
    badge: 'Hot Deal',
    href: '/shop/product/keto-kit',
  },
  {
    id: 3,
    title: 'Smart Sleep Tracker Band',
    price: '$39.99',
    originalPrice: '$79.99',
    rating: 4.9,
    reviews: 2100,
    image: 'https://picsum.photos/seed/sleeptracker/400/400',
    badge: 'Top Rated',
    href: '/shop/product/sleep-tracker',
  },
  {
    id: 4,
    title: 'Collagen Glow Serum',
    price: '$29.99',
    originalPrice: '$59.99',
    rating: 4.7,
    reviews: 1560,
    image: 'https://picsum.photos/seed/serum/400/400',
    badge: 'New',
    href: '/shop/product/collagen-serum',
  },
];

// Stats for hero section
export const heroStats = [
  { value: '90K+', label: 'Quizzes Taken' },
  { value: '9', label: 'Niche Categories' },
  { value: '1,400+', label: 'Products Curated' },
  { value: '4.9★', label: 'Average Rating' },
];
