// Quiz niches - 9 ClickBank funnels
export const quizNiches = [
  {
    id: 'weight-loss',
    title: 'Weight Loss',
    subtitle: 'Find your perfect plan',
    emoji: '🔥',
    color: '#FF5A5F',
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800',
    participants: '12,400+',
    href: 'https://toptierfind.com/why-cant-i-lose-weight',
  },
  {
    id: 'side-hustle',
    title: 'Best Side Hustle',
    subtitle: 'Find your income path',
    emoji: '💰',
    color: '#00A699',
    image: 'https://images.unsplash.com/photo-1553729459-efe14ef6055d?w=800',
    participants: '18,300+',
    href: 'https://toptierfind.com/best-side-hustle-2026',
  },
  {
    id: 'teeth',
    title: 'Teeth Problems',
    subtitle: 'Fix your smile',
    emoji: '🦷',
    color: '#FF5A5F',
    image: 'https://images.unsplash.com/photo-1606811841689-23dfddce3e95?w=800',
    participants: '6,500+',
    href: 'https://toptierfind.com/fix-teeth-problems/',
  },
  {
    id: 'relationships',
    title: 'What Men Want',
    subtitle: 'Strengthen your bond',
    emoji: '💕',
    color: '#FF5A5F',
    image: 'https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?w=800',
    participants: '11,600+',
    href: 'https://toptierfind.com/what-men-want-quiz/',
  },
  {
    id: 'woodworking',
    title: 'Woodworking',
    subtitle: 'Find your next project',
    emoji: '🪵',
    color: '#00A699',
    image: 'https://images.unsplash.com/photo-1601058268499-e52658b8bb88?w=800',
    participants: '5,700+',
    href: 'https://toptierfind.com/woodworking-project-finder/',
  },
  {
    id: 'blood-sugar',
    title: 'Blood Sugar',
    subtitle: 'Know your score',
    emoji: '🩸',
    color: '#FF5A5F',
    image: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=800',
    participants: '9,800+',
    href: 'https://toptierfind.com/blood-sugar-score/',
  },
  {
    id: 'dog-training',
    title: 'Dog Training',
    subtitle: 'Best method for your dog',
    emoji: '🐶',
    color: '#00A699',
    image: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=800',
    participants: '7,200+',
    href: 'https://toptierfind.com/best-dog-training-method/',
  },
  {
    id: 'septic',
    title: 'Septic Tank Problems',
    subtitle: 'Fix it before it spreads',
    emoji: '🚽',
    color: '#00A699',
    image: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800',
    participants: '4,300+',
    href: 'https://toptierfind.com/fix-septic-problems/',
  },
  {
    id: 'pineal-gland',
    title: 'Brain Booster',
    subtitle: 'Detox your pineal gland',
    emoji: '🧠',
    color: '#00A699',
    image: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=800',
    participants: '8,900+',
    href: 'https://toptierfind.com/detox-pineal-gland-quiz/',
  },
];

// Shop categories - 6 CJDropshipping
export const shopCategories = [
  {
    id: 'fitness-gear',
    title: 'Fitness Gear',
    description: 'Home gym essentials',
    image: 'https://picsum.photos/seed/fitnessgear/600/400',
    href: '/shop/fitness-gear',
    itemCount: '240+ items',
  },
  {
    id: 'wellness',
    title: 'Wellness',
    description: 'Health & self-care',
    image: 'https://picsum.photos/seed/wellness/600/400',
    href: '/shop/wellness',
    itemCount: '180+ items',
  },
  {
    id: 'kitchen',
    title: 'Kitchen & Diet',
    description: 'Cook smarter',
    image: 'https://picsum.photos/seed/kitchen/600/400',
    href: '/shop/kitchen',
    itemCount: '320+ items',
  },
  {
    id: 'beauty',
    title: 'Beauty',
    description: 'Look & feel your best',
    image: 'https://picsum.photos/seed/beauty/600/400',
    href: '/shop/beauty',
    itemCount: '410+ items',
  },
  {
    id: 'tech',
    title: 'Tech & Gadgets',
    description: 'Smart tools for life',
    image: 'https://picsum.photos/seed/techgadgets/600/400',
    href: '/shop/tech',
    itemCount: '290+ items',
  },
  {
    id: 'lifestyle',
    title: 'Lifestyle',
    description: 'Level up every day',
    image: 'https://picsum.photos/seed/lifestyle/600/400',
    href: '/shop/lifestyle',
    itemCount: '200+ items',
  },
];

// Featured products - placeholder (will be WP REST API driven)
export const featuredProducts = [
  {
    id: 1,
    title: 'ProFlex Resistance Bands Set',
    price: '$24.99',
    originalPrice: '$49.99',
    rating: 4.8,
    reviews: 1240,
    image: 'https://picsum.photos/seed/resistancebands/400/400',
    badge: 'Best Seller',
    href: '/shop/product/proflex-bands',
  },
  {
    id: 2,
    title: 'Keto Meal Prep Container Kit',
    price: '$18.99',
    originalPrice: '$34.99',
    rating: 4.6,
    reviews: 890,
    image: 'https://picsum.photos/seed/mealprep/400/400',
    badge: 'Hot Deal',
    href: '/shop/product/keto-kit',
  },
  {
    id: 3,
    title: 'Smart Sleep Tracker Band',
    price: '$39.99',
    originalPrice: '$79.99',
    rating: 4.9,
    reviews: 2100,
    image: 'https://picsum.photos/seed/sleeptracker/400/400',
    badge: 'Top Rated',
    href: '/shop/product/sleep-tracker',
  },
  {
    id: 4,
    title: 'Collagen Glow Serum',
    price: '$29.99',
    originalPrice: '$59.99',
    rating: 4.7,
    reviews: 1560,
    image: 'https://picsum.photos/seed/serum/400/400',
    badge: 'New',
    href: '/shop/product/collagen-serum',
  },
];

// Stats for hero section
export const heroStats = [
  { value: '90K+', label: 'Quizzes Taken' },
  { value: '9', label: 'Niche Categories' },
  { value: '1,400+', label: 'Products Curated' },
  { value: '4.9★', label: 'Average Rating' },
];
